--- #YAML:1.0
name:               Nagios-Status-Service
version:            0.02
abstract:           Nagios 3.0 Container Class for Status Services.
author:
    - Roy Crowder <rcrowder@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
